name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:  #manual trigger

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: |
        docker build -t majorelle.ca:${{ github.sha }} .

    - name: Stop and remove the old container
      run: |
        docker stop majorelle.ca || true
        docker rm majorelle.ca || true

    - name: Run the new Docker container
      run: |
        docker run -d --name majorelle.ca -p 8006:80 majorelle.ca:${{ github.sha }}
